### ISSUE TITLE
HMM has multiple emissions

### ISSUE THREAD

**Issue by zhaozx-cn** [NorskRegnesentral/weak-supervision-for-NER#1]
Hello,this work impresses me a lot about weak supervisions.However,I am not very clear about how to use Baum-Welch algorithm on a Hidden Markov Model has multiple emissions and how to use this model do annotation task. Could you please give me some illustration？Thanks a lot.

**Comment by plison** [comment]
Each emission is assumed to be independent (conditionally on the latent label), so the Baum-Welch algorithm is the same, except that the likelihood function computes a log-sum over the emissions of each labelling function instead of considering just one emission.  This is implemented in the file `labelling.py`.   Hope it answers your question!

**Comment by zhaozx-cn** [comment]
Sorry to bother you again! It seems that to aggregate multiple labelling functions, we have to compute probs through the code 
**probs = np.dot(X[:,source_index,:], self.emission_probs[source_index,:,:].T)** in the file **labelling.py**. This confuses me since the emission_probs means the probability from states to observations while X is the observation sequences. Is there something wrong or I misunderstand it?
